## Importing PyTorch

In [ ]:
import torch
torch.__version__

'2.0.1+cu118'

## Tensors

Tensors are the fundamental building block of machine learning.

### Creating Tensors

#### Scalar

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Check scalar dimensions
scalar.ndim

0

In [ ]:
# to get the python number within a tensor (only work with one element)
scalar.item()

7

#### Vector

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# check the number of dims of the vector
vector.ndim

1

In [ ]:
# check the shape of vector
vector.shape

torch.Size([2])

#### Matrix

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# check the number of dims of the MATRIX
MATRIX.ndim

2

In [ ]:
# MATRIX shape
MATRIX.shape

torch.Size([2, 2])

#### TENSOR

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# check the number of dims of the TENSOR
TENSOR.ndim

3

In [ ]:
# TENSOR shape
TENSOR.shape

torch.Size([1, 3, 3])

#### Random Tensors

In [ ]:
# create random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.6645, 0.4706, 0.2258, 0.9208],
        [0.4528, 0.9955, 0.5925, 0.4417],
        [0.1686, 0.3815, 0.8415, 0.2564]])

In [ ]:
# create random tensor of size (224, 224, 3)
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros

In [ ]:
# creates a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.shape, zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]),
 2)

#### Ones

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]),
 2)

#### Creating range of tensors

In [ ]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Tensor like

In [ ]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor datatypes

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
# tensor on float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

### Getting information from tensors

- shape - what shape is the tensor? (some operations require specific shape rules)

- dtype - what datatype are the elements within the tensor stored in?

- device - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
# create a tensor
some_tensor = torch.rand(size=(3,4))

# find details about it
print(some_tensor, "\n")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
print(f"Number of dimensions in tensor: {some_tensor.ndim}")

tensor([[0.5925, 0.4736, 0.7718, 0.0611],
        [0.2161, 0.3170, 0.0134, 0.8026],
        [0.1730, 0.7682, 0.6661, 0.7091]]) 

Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Device tensor is stored on: cpu
Number of dimensions in tensor: 2


### Manipulating tensors (tensor operations)

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
# PyTorch built in functions for above operations
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


In [ ]:
# Element-wise multiplication
print(tensor, "*" , tensor)
print("Equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


### Matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# same as above
tensor @ tensor

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 188 µs, sys: 0 ns, total: 188 µs
Wall time: 196 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 41.5 µs


tensor(14)

### One of the most common errors in deep learning (shape errors)

This will give an error 👇🏻

In [ ]:
# # Shapes need to be in the right way
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype=torch.float32)

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B)

In [ ]:
# view tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# after transpose tensor_B
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape} \n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same), tensor_B = {tensor_B.T.shape} \n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <-- inner dimesnions matching")
print("output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2]) 

New shapes: tensor_A = torch.Size([3, 2]) (same), tensor_B = torch.Size([2, 3]) 

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <-- inner dimesnions matching
output: 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

 Output shape: torch.Size([3, 3])


In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# this uses matrix multiplication
linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape} \n")
print(f"Output: \n{output}\n\nOutput shape {output.shape}")

Input shape: torch.Size([3, 2]) 

Output: 
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape torch.Size([3, 6])


### Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
# create a tensor
x = torch.arange(start=0, end=100, step=10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# perform some aggregation
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # <--- have to use type conversion
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# same operations as above
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max

find the index of a tensor where the max or minimum occurs with

In [ ]:
# create a tensor
tensor = torch.arange(start=0, end=100, step=10)
print(f"tensor: {tensor}")

# return indexes of maximum and minimum values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 9
Index where min value occurs: 0


### Change tensor datatype

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(start=10., end=100., step=10.)
tensor.dtype

torch.float32

In [ ]:
# Create a float16 tensor
float_16_tensor = tensor.type(torch.float16)
float_16_tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
torch_int8_tensor = tensor.type(torch.int8)
torch_int8_tensor

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing

In [ ]:
# Create a tensor
x = torch.arange(start=1., end=8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [ ]:
# Change view (keeps same data as original but changes view)
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
#  removing all single dimensions from a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
print(f"Previous dimensions: {x_reshaped.ndim}")

# Remove extra dimension from x_reshaped
x_squzeed = x_reshaped.squeeze()
print(f"New tensor: {x_squzeed}")
print(f"New tensor shape: {x_squzeed.shape}")
print(f"New dimensions: {x_squzeed.ndim}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])
Previous dimensions: 2
New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New tensor shape: torch.Size([7])
New dimensions: 1


In [ ]:
# add a dimension value of 1 at a specific index
print(f"Previous tensor: {x_squzeed}")
print(f"Previous tensor shape: {x_squzeed.shape}")
print(f"Previous dimensions: {x_squzeed.ndim}")


x_unsquzeed = x_squzeed.unsqueeze(dim=0)
print(f"New tensor: {x_unsquzeed}")
print(f"New tensor shape: {x_unsquzeed.shape}")
print(f"Previous dimensions: {x_unsquzeed.ndim}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous tensor shape: torch.Size([7])
Previous dimensions: 1
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New tensor shape: torch.Size([1, 7])
Previous dimensions: 2


In [ ]:
# rearrange the order of axes
x_original = torch.rand(size=(224,224,3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [ ]:
# Create a tensor
x = torch.arange(start=1, end=10, step=1).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

### PyTorch tensors & NumPy

In [ ]:
# NumPy array to tensor
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(size=(3,4))
random_tensor_B = torch.rand(size=(3,4))

print(f"Tensor A: \n {random_tensor_A} \n")
print(f"Tensor B: \n {random_tensor_B} \n")
print("Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A: 
 tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]]) 

Tensor B: 
 tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]]) 

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import random

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(size=(3,4))

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(size=(3,4))

print(f"Tensor C: \n {random_tensor_C} \n")
print(f"Tensor D: \n {random_tensor_D} \n")
print("Does Tensor C equal Tensor D?")
random_tensor_C == random_tensor_D

Tensor C: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

Tensor D: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

Does Tensor C equal Tensor D?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors on GPUs (and making faster computations)

In [ ]:
!nvidia-smi

Wed Aug 23 03:31:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# creatting device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# check the number of GPU device count
torch.cuda.device_count()

1

#### Putting tensors (and models) on the GPU

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

# move tensor to GPU
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

#### Moving tensors back to the CPU

Do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU)

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
# tensor_on_GPU.numpy() # <---- this will given an error since numpy only works on cpu

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_GPU.cpu()
tensor_back_on_cpu.device

device(type='cpu')